name: First Workflow

on: [push]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Hello Quimis!
              run: echo "Hello!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }} "

            - name: More and Moree
              env: 
                  JOB_CONTEXT: ${{ toJson(job) }}
                  GIT_HUB_ENV: ${{ toJson(vars) }}
                  SECRETS_ENV: ${{ toJson(secrets) }}
              run: |
                  echo "Job Context: $JOB_CONTEXT"
                  echo "valor del primere secret : ${{ secrets.PASS_ONE }}"
                  echo "valor de la primera variable: ${{ github.VAR_ONE }}"
                  echo "valor de la primera variable github: $GIT_HUB_ENV"
                  echo "valor de los secrets: $SECRETS_ENV"
                  echo Done
              
