name: First Workflow

on: [push]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Hello Quimis!
              run: echo "Hello!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }} "

            - name: More and Moree
              env: 
                  JOB_CONTEXT: ${{ toJson(job) }}
              run: |
                  echo "Job Context: $JOB_CONTEXT"
                  echo "valor del primere secret : ${{ secrets.PASS_ONE }}"
                  echo "valo de la primera variable: ${{ env.VAR_ONE }}"
                  echo Done
              
